/* =================================================================
 *
 * Copyright (C) 2019 anonymoussoft.com.  All rights reserved.
 * File: button.cpp
 * Time-stamp: <2019-02-26 11:34:10>
 * Description:
 * Author: bin.gao
 *
 * =================================================================
 */

#include "./button.h"

LUACOB_BIND_CLASS_BEGIN("Button", LButton)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(setButtonText)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(getButtonText)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(isDown)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(isOver)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(setToggleState)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(getToggleState)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(getToggleStateValue)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(setClickingTogglesState)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(getClickingTogglesState)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(setRadioGroupId)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(getRadioGroupId)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(addListener)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(removeListener)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(triggerClick)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(setCommandToTrigger)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(getCommandID)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(addShortcut)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(clearShortcuts)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(isRegisteredForShortcut)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(setRepeatSpeed)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(setTriggeredOnMouseDown)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(getTriggeredOnMouseDown)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(getMillisecondsSinceButtonDown)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(setTooltip)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(setConnectedEdges)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(getConnectedEdgeFlags)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(isConnectedOnLeft)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(isConnectedOnRight)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(isConnectedOnTop)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(isConnectedOnBottom)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(setState)
LUACOB_BIND_CLASS_MEMBER_FUNCTION(getState)
LUACOB_BIND_CLASS_END()
